#Server
server:
  port: 8080
  error:
    include-stacktrace: never

#CrossOrigins
client:
 url: http://localhost:4200

spring:
  application:
    name: warehouse-rest
    zipkin: http://localhost:9411
  datasource:
    driver-class-name: org.h2.Driver
    username: a
    password: a
    url: "jdbc:h2:mem:jsilgado;DB_CLOSE_ON_EXIT=FALSE"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  
      
#jwt
app:
 security:
   enabled: true
 timeZone: 
 jwt-secret: JWTSecretKey
 jwt-expiration-milliseconds: 604800000
