#CrossOrigins
client:
 url: http://localhost:4200

server:
  port: 8080
  servlet.context-path: /

spring:
  application:
    name: warehouse-rest
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    continueOnError: true
  jpa:
    open-in-view: false #Controls whether JPA keeps the session open during the view
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
       hibernate.metadata_builder_contributor: io.github.acoboh.query.filter.jpa.contributor.QfMetadataBuilderContributor #Query Filter JPA Spring Boot 2.7.x in 3.X is not neccesary 


#jwt
app:
 jwt-secret: JWTSecretKey
 jwt-expiration-milliseconds: 604800000
 
#swagger
springdoc:
  swagger-ui:
    display-request-duration: true #Enables the display of request duration in the Swagger user interface.
    tags-sorter: alpha #Specifies how to order tags in the Swagger user interface.
    operations-sorter: alpha #Specifies how to order operations in the Swagger user interface
    
 
#actuator 
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans" 
