#CrossOrigins
client:
 url: http://localhost:4200

spring:
  application:
    name: warehouse-rest
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    continueOnError: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      
#jwt
app:
 jwt-secret: JWTSecretKey
 jwt-expiration-milliseconds: 604800000
 
#swagger
springdoc:
  swagger-ui:
    enable-auth: true
    auth-scheme: bearer
    display-request-duration: true
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
    
 
#actuator 
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans" 
